apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: inventory
type: Opaque
data:
  hosts: QkFTRTY0RU5DT0RFRF9QUk9WSURFUl9DUkVEUw==
---
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: secret-inventory-remote-debug
spec:
  forProvider:
    inventories:
      - source: Secret
        secretRef:
          namespace: crossplane-system
          name: inventory
          key: hosts
    # AnsibleRun default to using a remote source.
    # For simple cases you can use an inline source to specify the content of
    # playbook.yaml as opaque, inline yaml.
    playbookInline: |
      ---
      - hosts: all
        tasks:
          - name: ansibleplaybook-simple
            debug:
              msg: Your are running 'ansibleplaybook-simple' example